### ISSUE TITLE
Share Invite Link in "add buddy" dialog crashes

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#102]
This is an immediate crash when select to share invite link (share via SMS and QR code work) on the latest testflight from yesterday.

@chrisballinger can you reproduce on your end and/or test if is same in ChatSecure?

**Comment by chrisballinger** [comment]
Works fine over here, but we don't support sharing links from the add buddy screen upstream. 

The ShareController requires a UIView for the sender parameter otherwise the popover will crash on iPad: https://github.com/ChatSecure/ChatSecure-iOS/blob/develop/ChatSecure/Classes/Controllers/ShareController.swift#L20

**Comment by n8fr8** [comment]
Why don't you sharing invite links upstream? Do you have the "invite" tab at all?

It would be good to keep track of things that are Zom only so we know what to more thoroughly test and maintain.

**Comment by N-Pex** [comment]
Yes, thanks Chris, that was it! Did the change and checked it in.
