### ISSUE TITLE
improve final onboarding screen

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#133]
https://github.com/zom/Zom-Assets/blob/master/designdocs/Zom%20iOS%20onboarding%20screen%204.pdf

![download 1](https://cloud.githubusercontent.com/assets/30851/15440507/c813c992-1ea3-11e6-82dc-00dedf15234b.png)

**Comment by N-Pex** [comment]
@chrisballinger @davidchiles Is there currently a way to set the avatar in the underlying code? I found a setAvatarData() API in OTRAccount that looks promising, but I don't think I got that to work?

**Comment by gekhung** [comment]
[Zom iOS onboarding screen 4.pdf](https://github.com/zom/Zom-iOS/files/302597/Zom.iOS.onboarding.screen.4.pdf)
[Zom iOS onboarding screen 4 without avatar option.pdf](https://github.com/zom/Zom-iOS/files/302596/Zom.iOS.onboarding.screen.4.without.avatar.option.pdf)

**Comment by gekhung** [comment]
Here is an updated version of Zom iOS onboarding screen 4. The current version used has password missing in the text  + it's showing line in the middle which was between the Congratulation screen on top and avatar option below.  I have shared above the graphic with and without avatar option in case for future ;)

**Comment by n8fr8** [comment]
@gekhung PDF Is a terrible format for app graphics. We need these in PNG please.

**Comment by N-Pex** [comment]
Ok, I changed the text. The avatar part is just hidden for now, waiting for avatar support in upstream.

@chrisballinger Is this planned?

@n8fr8 In the onboarding now I try to use the same strings as Android, so that we can pull the translations from Android automatically using my script. However, changing this string breaks that, so that we will need separate translations on iOS. Maybe not a big deal, we'll probably have iOS-spcific strings anyway, but something to keep in mind...

**Comment by gekhung** [comment]
![zomios-screen04-no-avatar-01](https://cloud.githubusercontent.com/assets/11950115/16043579/531f1212-320e-11e6-8c65-e59342d2e551.png)

**Comment by gekhung** [comment]
![zomios-screen04-no-avatar-01](https://cloud.githubusercontent.com/assets/11950115/16043738/2d3a0768-320f-11e6-8594-34b5d8b22b93.png)
![zomios-screen04-with-avatar-01](https://cloud.githubusercontent.com/assets/11950115/16043744/321b3ca2-320f-11e6-95c6-fb4333f8fa74.png)
