### ISSUE TITLE
Still problems with audio messaging

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#147]
I just setup Zom on a brand new iPod Touch. I created a new account, and connected with my Android phone. All works well, including sending photos and stickers.

However, audio messaging does not work. If I send from iPod, the audio messaging is always stuck at "waiting...". If I send from Android to iPod, it is always stuck at "0%" and never receives.

From iPad to iPod, the audio seems to transfer, but then the receive side is still unplayable and stuck at 0:00 timing.

Both iPod and iPad are on dukgo.com. My android is my @guardianproject.info account.

**Comment by n8fr8** [comment]
Sending from iOS and receiving on Android side, we are not receiving the File-Hash-SHA1 header, and the File-Length is 0.

0 = {BufferedHeader@6871} "File-Name: A7AFF0A3-5C45-489D-A3AC-726BBA4F1CA1.m4a"
1 = {BufferedHeader@6874} "Mime-Type: audio/x-m4a"
2 = {BufferedHeader@6889} "File-Length: 0"
3 = {BufferedHeader@6890} "Request-Id: B9F9CFDE-917E-40A5-AF6E-3D5B4306A8F7"

I feel like we fixed this before.

**Comment by chrisballinger** [comment]
I think I've seen that for the first audio recording, and then the second one succeeds. Also is there any chance that the microphone permission isn't enabled?

**Comment by n8fr8** [comment]
In the past it was something that @davidchiles found about app permission flags in the plist / configs or something? Maybe something is not making it down from the base project?

The app definitely has mic permissions.

**Comment by chrisballinger** [comment]
Okay there's definitely something wrong because it doesn't even play back locally. It initially shows a duration but then when you try to play it's 0:00. Maybe there's something wrong with IOCipher.

Another possible problem could be that iOS is being more strict about HTTPS for the media web server. Oh, another problem is that we hard-code the port so the media server will fail to start up if you're running both ChatSecure and Zom.. or another thing that runs on 8080.

**Comment by davidchiles** [comment]
Here's what I found so far (Using develop branch at https://github.com/ChatSecure/ChatSecure-iOS/commit/f954a9b8066d96da4189397dabae05328d7a4948 unless otherwise stated):

**ChatSecure-testflight** to **ChatSecure-simulator**: See the problems on Chatsecure-testflight but everything works on simulator.

**ChatSecure-local-build-device** to **ChatSecure-simulator**: Everything seems to work on both clients.

I was even able to set `NSAllowsArbitraryLoads` to `false` and kept the `NSExceptionDomains` for `localhost` and it kept on working. I'm not sure what is different about the testfight build that would be causing this problem. It does look like the problems are caused by not being able to access the media server at `localhost`.

**Comment by davidchiles** [comment]
Maybe adding more keys will solve the problem 😃 
https://bencoding.com/2015/07/20/app-transport-security-and-localhost/
```
<key>NSAppTransportSecurity</key>
<dict>
   <key>NSExceptionDomains</key>
   <dict>
       <key>localhost</key>
       <dict>
        <key>NSTemporaryExceptionAllowsInsecureHTTPSLoads</key>
           <false/>           
           <key>NSIncludesSubdomains</key>
           <true/>
           <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
           <true/>
           <key>NSTemporaryExceptionMinimumTLSVersion</key>
           <string>1.0</string>
           <key>NSTemporaryExceptionRequiresForwardSecrecy</key>
           <false/>
       </dict>
   </dict>
</dict>
```

**Comment by n8fr8** [comment]
@N-Pex maybe we should add these?

**Comment by chrisballinger** [comment]
I found some crash issues regarding microphone permissions. We never asked for the permissions, or had a permission description set, so it would crash on iOS 10. Also fixed a UI issue where the microphone UI wouldn't go away after dismissing the permission dialog.

Also make sure `NSMicrophoneUsageDescription` is set in Zom's `Info.plist`.

Still haven't been able to reproduce the zero-length issue..

**Comment by N-Pex** [comment]
@chrisballinger Thanks. We also had to add NSCameraUsageDescription and NSPhotoLibraryUsageDescription (Apple sent an email after upload). Do we also need to ask for permission for these, or we already do perhaps?

**Comment by chrisballinger** [comment]
We ask for camera permission during the QR code stuff. The stock UIPickerController should handle asking the permissions.
