### ISSUE TITLE
debug iOS 8.4 / iPhone 4S issues

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#15]
checkboxes in the menu don't appear and other small glitches that block basic functionality

**Comment by chrisballinger** [comment]
@n8fr8 See my comment on Slack.. turns out this is now 100% impossible to debug on hardware due to Apple's restrictions on updating devices to only the latest iOS versions. iOS 8.4.1 is basically impossible to install now because Apple has stopped signing it (the device phones home while flashing). Users will have to update to iOS 9 sooner than I expected... and despite the challenges faced by poor internet connectivity in remote areas.

In order to help people with slow internet, I am preparing a BitTorrent magnet link that contains the full iOS 9.1 firmware for every supported device. Turns out that's still a lot of devices, going all the way back to the iPad 2 and iPhone 4S era! I'll try to make sure it fits on cheap encrypted USB sticks if possible. Will share more details later about the format, instructions, and link info after I finish the bundle.

Posting new build tomorrow I promise!

**Comment by N-Pex** [comment]
@chrisballinger Running iPhone 4s on 8.4 simulator I can see a lot (all?) of the images missing.

Log output shows: 

2015-11-20 20:14:30.574 Zom[12649:1822322] -[CUIThemeRendition newImageFromCSIDataSlice:ofBitmap: usingColorspace:] Unsupported pixel format in CSI got 4
2015-11-20 20:14:30.574 Zom[12649:1822322] Unable to create unsliced image from csi bitmap data.

Googling this I see this is most commonly caused by having JPEGs in image assets, but I don't think there is? Anyhow, symptoms and cures seem a little vague, like "It worked when I reinstalled XCode".
