### ISSUE TITLE
autogenerate nickname/display name from jabberid

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#152]
if the jabberid of a new incoming contact is foo.1234@foo.com, we should parse that to set the display nickname to just "foo"

**Comment by chrisballinger** [comment]
I don't think that's the right way to do it, because it will result in problems for JIDs like "firstname.lastname@ex.com", or really any other use of "."

The correct way to handle this would be to properly support vCard Display Name during account creation, since we already handle those fields for incoming contacts. 

There may be other issues if multiple people in your contacts have the display name "Tenzin", but that would happen regardless of how this is handled.

**Comment by n8fr8** [comment]
There is a short term need to have more usable display of names when there is no nickname set. If you just want to use the @ as a separator that would also be fine. 

vCard Display name + avatars and more would be great, but as a short term solution, it would be good to have a better way to display a friendly name for contacts who only provide a jid.

**Comment by chrisballinger** [comment]
I think this is something that I will want to keep different upstream, but I'll think about it some more. Perhaps we could make full JID display configurable in preferences and just set Zom to a different default.

**Comment by N-Pex** [comment]
Ok, for now I added the parse like this: if no nickname is set, discard anything after "@". Further, if the resulting string ends with . followed by 4 to 8 hex characters, strip them.

**Comment by n8fr8** [comment]
This looks good though now another issue... there is no way to actually see their full jabber id at all, since there is no profile, info screen, etc. 

Would it be possible to have the contact / new chat picker list show the nickname AND the jabber id, like we do with Android?

Or is there somewhere else you can easily see this?

**Comment by N-Pex** [comment]
Ok, yes, I did that now. However, this has the side effect of cluttering the screen when you have more than one account configured in Zom, since you then have thee rows: 1. User 2. User@example.com and 3. Youraccount@example.com. But for now, probably better to be able to see the full jid.
