### ISSUE TITLE
add buddy view controller not prompting for camera permission

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#164]
changes in ChatSecure causing a critical issue for new installs of Zom

**Comment by chrisballinger** [comment]
I don't think this is related to changes upstream since those aren't even
used in Zom anymore. It's just that the camera permission isn't being
handled properly in the Zom QR Scan UI.

Adding this fallback dialog should help:
https://github.com/ChatSecure/ChatSecure-iOS/blob/develop/ChatSecure/Classes/View%20Controllers/Onboarding/EnablePushViewController.swift#L73

**Comment by n8fr8** [comment]
Can we have the dialog work even without the permission? So that just the QR display and link options work, but the camera is black?

**Comment by chrisballinger** [comment]
Just reproduced by turning off camera permission and causes a crash for me.
Resolves when turning back on permission.
