### ISSUE TITLE
(i) Icon on the top right in chat should display the contact's profile

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#169]
People are confused with the info icon in chat on top right. They think that they have to verify in order to start encrypted chat.

**Comment by gekhung** [comment]
Is there an interim or easy fix to info icon confusion? - remove stop encryption option

**Comment by n8fr8** [comment]
Yes, we'll see. Maybe not in this weeks build, but soon.

**Comment by n8fr8** [comment]
This will now take people to the new contact profile view, right?

**Comment by cstiens** [comment]
Here is the current view of a friend's profile on Android, displayed when you tap the 'i' icon within a chat with someone.
![screenshot_20161205-142841](https://cloud.githubusercontent.com/assets/1434597/20901289/73f46150-baf7-11e6-8cca-122909660cf2.png)

**Comment by davidchiles** [comment]
Current ChatSecure profile: <img width="432" alt="screen shot 2016-12-05 at 12 33 53 pm" src="https://cloud.githubusercontent.com/assets/309772/20901381/1fef5264-bae7-11e6-8f9d-c82247d4143d.png">

**Comment by cstiens** [comment]
Currently in Zom, when you tap on the 'i', it prompts you to verify the person you're chatting with. It does this even if you have already verified the person. 
@N-Pex We need to add the profile view (like on Android) for friends. 
We can keep the prompt to verify a friend at the top of the conversation screen. But, it should only be shown if the person needs to be verified. And, it should not be hidden when the 'i' is tapped.

**Comment by cstiens** [comment]
@N-Pex @chrisballinger @davidchiles Let's keep the layout of the account info as it is in Chatsecure (like the screenshot David added). We need to make some additions to match Android in terms of the elements and actions that are in this view. Here's the run down of what we need to show:

Info
- User's nickname
- User's full ID name
- Secure ID (alpha numeric string)
- QR code

Actions:
- share QR code
- verify
- start chat

@chrisballinger @davidchiles In the image, do we need to keep the 'OTR' label or 'TOFU' switch for any reason?

![img_0009](https://cloud.githubusercontent.com/assets/1434597/21064276/8a22950c-be1f-11e6-8a42-6dfdbbe055a3.JPG)

**Comment by chrisballinger** [comment]
@cstiens

* There is a difference between OTR and OMEMO fingerprints, so they are marked accordingly in the UI. A contact can accumulate many different OTR and OMEMO fingerprints during the lifetime of their account. 
* The TOFU label can also have values of "Untrusted", and "Verified". TOFU means "Trust on First Use", which means it's a fingerprint that has been implicitly trusted because it was the first one that was seen. There is probably something better than TOFU like "Initially Trusted", "Preliminary Trust" or similar.
* The area you marked for Nickname is already the nickname, there just wasn't one at the time, so it showed the JID again. We should at least strip the domain and pretend there is a nickname.
* The QR code icon can be added upstream, but I think it should be folded into the Verify button instead. See discussion below.
* Show Advanced ideally wouldn't be required if you are ~100% certain Zom users will only talk to other Zom users.
* The on/off switch is there for an important reason, so you can manually alter the trust state of a specific device/fingerprint. Delete is implemented by an iOS-native "swipe left" gesture.
* Currently, pressing on the cell itself shares the fingerprint, but users should be encouraged to instead do a full "Verify".
* "Verify" button should be added upstream.
* "Start Chat" doesnt make much sense because you can only get to this view from a chat. 
* The section for your own OMEMO / OTR fingerprints can be moved to another view, but you'll still need a way to get to the associated account.

Discussion:

* Doing a "Verify" should compare all devices and fingerprints for each user simultaneously. This means the idea of a QR code button for a single fingerprint is not ideal because each user can have many devices. The user should have the option to do a full QR code compare, or do a compare over Email, SMS, or any other out-of-band app that can handle text. This should be handled by native iOS UIActivities that appear in a Share Sheet presented by the Verify button.

**Comment by cstiens** [comment]
Done
