### ISSUE TITLE
Updated add friend UI

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#197]
![0d105292-80b3-11e6-9318-5995d79fe4af](https://cloud.githubusercontent.com/assets/30851/20764280/860ca244-b6fb-11e6-9a34-ced0b9b13081.png)

**Comment by cstiens** [comment]
@N-Pex  Almost there. 
- Please add the text to the right of the icons indicating the action (i.e. sms, share, and scan)
- Please match the sms and scan icon to android
- Please use the standard iOS share icon instead of the android share.
*Note: Using pink for the icons (rather than white with a gray outline) is preferred.

- When I tap on the input area, the keyboard covers up the text I'm typing. This is on the iPhone 6. The easiest fix is to move the descriptive text ('Enter your friend's full username...) below the input box. Though we may run into the same issue on iPhone 4 screens. Alternatively, we could scroll the page up when the keyboard opens. Mikael, I'll leave this decision to you.

**Comment by N-Pex** [comment]
@cstiens Please re-test in the latest version.

**Comment by cstiens** [comment]
@N-Pex The view is scrolling correctly when the keyboard opens. What I'm typing is visible, but feels scrunched. Can you scroll the page up further, so that the 'advanced' title is just below the top bar? This is a minor adjustment that can be considered low priority for now.

Secondly, I'm not sure what happened, but the icons at the top have gone out of view. See screenshots.

![img_0019](https://cloud.githubusercontent.com/assets/1434597/21107679/2abd7f7e-c058-11e6-8ab0-b578f4a6564f.PNG)


![img_0018](https://cloud.githubusercontent.com/assets/1434597/21107682/2e580b9a-c058-11e6-93f3-1a9d065fea0c.PNG)

**Comment by N-Pex** [comment]
@cstiens Yes, I just noticed the thing with the icons, I am in the process of fixing. I'll have a look at the scrolling at the same time!

**Comment by cstiens** [comment]
@N-Pex I'm testing this in version 53, and the scroll is great! The 'sms' text and icon are larger than the other 2, causing the word to get clipped. See screenshot. 

![img_0027](https://cloud.githubusercontent.com/assets/1434597/21155164/9a5cc522-c136-11e6-8e60-90a9f493a279.PNG)

**Comment by cstiens** [comment]
@N-Pex we need to use the ios action share for the 'share' option to stay consistent within the app.
<img width="751" alt="screenshot 2016-12-13 13 39 17" src="https://cloud.githubusercontent.com/assets/1434597/21199175/fac1cb98-c207-11e6-94a2-b10e785ac24d.png">
