### ISSUE TITLE
Show a double check when a message is received

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#208]
@chrisballinger and @davidchiles In the Android UI, we show a double check when the person I send a message to has seen it. On iOS, is it possible to know when the other person has received the message?

**Comment by davidchiles** [comment]
Yes we can show a checkmark when a message actually leaves the device and another check mark when we receive a delivery receipt. I can look into the best way to customize this for zom/chatsecure differences

**Comment by n8fr8** [comment]
Currently, iOS just shows one check. I never see a second checkmark. Did something change in the code that we may have not merged from upstream?

**Comment by n8fr8** [comment]
Also, we show a clock while they are queued or waiting to send. In short, we match what WhatsApp does.

**Comment by chrisballinger** [comment]
@n8fr8 The current states upstream are:

- Clock icon for pending queue status (connecting to account, negotiating OTR, fetching OMEMO devices, sending to network, etc)
- No icons for "sent to network" (except for upstream OMEMO/OTR lock stuff)
- 1x check mark for delivered

This could be changed to:

- Clock icon for pending queue status
- 1x check mark for sent to network
- 2x Check mark for delivered

@cstiens "Read receipts" are different than delivery receipts, and we will need to implement [XEP-0333: Chat Markers](http://xmpp.org/extensions/xep-0333.html) on both iOS and Android.

The UI I am planning for upstream for read receipts is similar to Facebook and Hangouts. It simply puts a ring around the avatar corresponding to the last message marked as read.

**Comment by n8fr8** [comment]
The proposed changes matches WhatsApp. I think having nothing is confusing, so always having an indicator is best.

Yes, right now we just want delivered receipts, not read receipts yet.

**Comment by n8fr8** [comment]
@N-Pex is getting this code from upstream possible in the current timeframe?

**Comment by chrisballinger** [comment]
It should be possible to alter this upstream with minimal changes, but the develop branch doesn't contain the message queue (which modifies the annotation behavior) so it may need to be re-applied after the omemo branch merge. It would probably just need to be re-done in Zom for now but I'll check with David since he's the one who worked on the message queue and new annotation behavior.

The single checkmark is interesting because in most contexts it means that the remote server has acknowledged the message, but it is impossible to do that with XMPP unless you are using XEP-0198 (which Dukgo doesnt support). In our case I guess it would mean there was an attempt at sending the message over the network and it at least made it off of the device.

**Comment by chrisballinger** [comment]
Fixed

**Comment by cstiens** [comment]
This seems to be working. Thank you Chris! There's one difference from Android -- In iOS I see a single check next to the recipient's messages I receive. I'm not sure what this means. But, on Android, we only show checks on the messages the user sends. @chrisballinger @n8fr8 Can we eliminate the check next to the received messages?

Here's a side by side comparison.

<img width="966" alt="screenshot 2016-12-15 10 57 59" src="https://cloud.githubusercontent.com/assets/1434597/21233113/a3f62122-c2b3-11e6-9b51-451b1ec7aece.png">

**Comment by chrisballinger** [comment]
Ok should be fixed now

**Comment by cstiens** [comment]
Yep! It's fixed
