### ISSUE TITLE
Get OMEMO working with Zom

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#264]
@davidchiles Please put the list of things that need to happen for OMEMO to be enabled for Zom here.

**Comment by davidchiles** [comment]
## Device/Key Management
- [ ] Ability to remove other devices that are connected to your XMPP account.
- [ ] Ability to trust/untrust your own devices and buddies devices

The above is implemented in ChatSecure. The only question is how will it look in Zom. Seems to me the profile view is the most likely candidate. Maybe a new section to split apart OTR and OMEMO?

## Open Questions
- [ ] Should users be able to chose what type of encryption they use OTR/OMEMO or should we always use 'best available'? 

The concern here is that 'best available' may be OMEMO but the current device their buddy is using doesn't support OMEMO. For example a user that has Zom-Android and Zom-iOS. Because iOS will add a device to the XMPP account but Zom-Android won't be able to decrypt the messages until OMEMO is implemented for Android. But the user could force Zom-iOS to use OTR which would allow messages to be decrypted.

- [ ] How should 'Trust on first use' work?

Easiest to keep it the same as ChatSecure which is first time a device list is fetched all those devices are considered trusted. Any additions after that first fetch need to be trusted manually.

**Comment by cstiens** [comment]
Last week we decided to implement OMEMO in Zom the same way it's implemented in Chatsecure, then making the Zom specific adjustments from there.

**Comment by d9h02f** [comment]
@davidchiles Regarding 3) I think there is nothing to gain in keeping OTR at all once OMEMO is available, especially in a client which aims for ease of use. Zom should be OMEMO-exclusive. If this means Zom-iOS users won't be able to communicate with Zom-Android users until Zom-Android also gets OMEMO, it's probably best to just hold off on releasing either until they're both ready to roll.
