### ISSUE TITLE
Push notification for upgrading

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#294]
Each time the user opens the app (until they upgrade or until May 9th), show a push notification prompting them to upgrade.

Here's the text:
“Your account is expiring in 'x' days”   
Button options: 
More / Upgrade Now
- more takes the user to the account upgrade info screen
- upgrade now initiates the migration process (the same as tapping upgrade in the conversation view prompt)

@N-Pex After our conversation today, this may be more complicated to implement than it seems. Let me know if we need to discuss alternatives.

**Comment by N-Pex** [comment]
@cstiens Unless I am wrong you can only have ONE action on a local alert. Also, wouldn't this be pretty redundant since you are starting up on the conversations view anyway and seeing the header?

**Comment by chrisballinger** [comment]
Custom actions on notifications aren't particularly discoverable, and the
header is already being shown so there's not really a reason to show the
info twice.

Additionally these actions are only available on iOS 10. My only plans for
custom alert actions at the moment are to support inline replies because
that hooks into native iOS functionality like replying from your watch.
