### ISSUE TITLE
Block the ability to chat with person that is in the archive

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#307]
Your pre-existing conversations are stored in the archive. We want to block the ability to continue to send messages to accounts that are archived. To chat with that person, you would need to unarchive them, and start a chat from the inbox or active tab.

This should be true for the Convo archive and in the Friends archive.

@n8fr8 please fill in details as needed.

**Comment by N-Pex** [comment]
Fixed in this PR https://github.com/ChatSecure/ChatSecure-iOS/pull/762. This of course has the effect that archived conversations can't be read unless they are first unarchived, which seems a little bit odd. @cstiens Maybe we should just show the conversations, but disable/remove the send functionality? Requires a little more work though.

**Comment by n8fr8** [comment]
Yes I think we wanted to disable send and notification. You should still be able to read and even receive. This can also be used effectively as a "mute" feature. I often need this to end conversations with random people contacting me for tech support.

**Comment by N-Pex** [comment]
Ok, changed the implementation now so that send is completely hidden (@cstiens in an ideal world we would show some information I guess? If the buddy was archived because of migration then we WILL show the "Chat Now" view, but in the case when you manually archive a friend we don't show that)
