### ISSUE TITLE
When you accept a friend request the 'waiting for a friend request' flashes

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#316]
When you accept a friend request, the 'waiting for a friend request' flashes before you begin a new chat with them. It flashes for 1 second before showing the 'one moment please' view.

This is happening consistently in our tests.

**Comment by N-Pex** [comment]
@cstiens I think this has to do with "being friends with someone" is a directed edge in XMPP - just because I consider you my friend you don't have to consider me your friend.

@chrisballinger How is the flow here? If I "add a friend" then a subscription request is sent, but shouldn't I automatically start sending you presence?
