### ISSUE TITLE
Add Tibetan translation for Inbox / Archive

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#331]
@N-Pex 
![img_0256](https://cloud.githubusercontent.com/assets/1434597/25960987/4a25aec0-363e-11e7-85f6-edb2f301cc74.PNG)

**Comment by N-Pex** [comment]
Strange, I had those in there at one point, let me look.

**Comment by N-Pex** [comment]
@cstiens How are you testing this? Works for me (well, not the "Add Friend" but this issue). i have "prefer Tibetan" in my settings. By the look of your clock at the top of the screen you don't... =)

![simulator screen shot 11 maj 2017 19 29 23](https://cloud.githubusercontent.com/assets/5418622/25963019/2aa9a028-3680-11e7-9e1c-4809843e7bb8.png)

**Comment by cstiens** [comment]
@N-Pex I began with a fresh install of Zom, and chose Tibetan as the language on the very first Zom screen.

**Comment by cstiens** [comment]
Tested this morning, and Inbox/Archive still in English. As well as the 'Congratulations' Screen is still in English. 
![img_2305](https://cloud.githubusercontent.com/assets/1434597/26359840/22c40900-3f9c-11e7-8906-385ad8a2700a.PNG)

**Comment by N-Pex** [comment]
Ok, I changed the "Add friends to Zom" string to "Add Friends" now, so I could use all existing translations from Android.

The first problem is related to that changing language "in app" is not really supported by Apple, so any way you implement it you are going to end up with a "hack" of sorts. I changed the implementation now, so that it should work better(?). @cstiens My guess is that if you restart Zom you'll get the correct strings, right?
