### ISSUE TITLE
Because OTR session has started, it doesn’t switch to OMEMO

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#337]
Here's the case:
I scanned L's phone, got Pending Approval/Waiting for your friend to accept you. After L had approved me both sides still said "One moment please! We're preparing your private Zom." It was stuck like this for a long time. Eventually Lobsang did a session refresh and then we were able to chat. Note: The app was using OTR.

This is what should happen: 
- Don’t start OTR until you are friends
- If you’re in an OTR session, make sure it switches to OMEMO
- Queue messages sent before the session establishes (show clock) 

I'm tagging @n8fr8 on this ticket because he helped troubleshoot.

**Comment by N-Pex** [comment]
@chrisballinger Not sure this is the right ticket, but... I spent the day in the debugger here, trying to figure out this subscription thingy. You are right that the subscription status ends up "half way", but I can't see that it would be because of my changes.

If A adds B (I am testing using "Add Friends" -> type username) then B will get the "Approval cell" in Bs conversations list. Once B approves, A will in turn receive a subscription request in XMPPRoster.m which it will automatically approve. For some reason, this doesn't work(?) I can see that we end up with B subscribing "from" A and A subscribing "to, request received" B.

**Comment by N-Pex** [comment]
Finally tracked this down, should be fixed in version 84.
