### ISSUE TITLE
Regenerate local OMEMO key if missing

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#347]
One of our team, TL, has an account setup on her phone that seems to have no local OMEMO key generated. Only the OTR key is showing. She has had this phone and account setup for awhile, before OMEMO support was in, so perhaps that is related to this problem? Anyway to detect it is missing and auto reg?

**Comment by chrisballinger** [comment]
This is likely due to some longstanding flaws in the OMEMO storage implementation. Sessions and other info are keyed to the buddy username instead of unique id, or account uniqueid+buddyusername, so collisions can happen and break everything. I should have caught this during code review a year ago, but it slipped by and it's not simple to fix without needing a database migration. There are also issues with libsignal-protocol-c where it sometimes cannot generate valid bundles, that I think are linked to the above.

**Comment by n8fr8** [comment]
Maybe I should just ask her to delete the account and add it again?

**Comment by chrisballinger** [comment]
You might need to completely delete the app if it's caused by the above problem..

**Comment by n8fr8** [comment]
Yes we did that. All is fine now.
