### ISSUE TITLE
Default group chat avatars

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#349]
@N-Pex I've attached 1 default group chat avatar. In the end, we will have multiple that are randomly selected, but this will give you something to work with. There's a png and pdf. 

![av_group01](https://user-images.githubusercontent.com/1434597/28028983-07e58c38-6564-11e7-9852-c51a417fce61.png)
[av_group01@1x.pdf](https://github.com/zom/Zom-iOS/files/1136381/av_group01.1x.pdf)

**Comment by n8fr8** [comment]
Oh, I think we need this for Android to, yes?

**Comment by N-Pex** [comment]
@cstiens Since the existing avatar code actually does the rounding for us, I did not want the image to be already rounded. I came up with the idea of actually generating the group chat avatars on the fly. They now consist of three horizontal fields, randomly "slanted", with random colors (currently only picked form the three you provided, should probably be more...). How do you like this approach?

@chrisballinger Something for upstream as well?

![simulator screen shot 20 juli 2017 17 43 10](https://user-images.githubusercontent.com/5418622/28426284-02a47bc8-6d73-11e7-89d0-481ba4053858.png)

**Comment by N-Pex** [comment]
Oh, another reason for doing this was that we can handle the "big avatar image" for groups (in issue #348) with the same drawing code. It's only pseudo-random and seeded with the unique id of the group chat, so regardless of if we make a small image or a large one we'll get the same colors and slanting! =)

**Comment by cstiens** [comment]
> I came up with the idea of actually generating the group chat avatars on the fly. They now consist of three horizontal fields, randomly "slanted", with random colors (currently only picked form the three you provided, should probably be more...). How do you like this approach?

@N-Pex I love it! I like the randomness and that we'll get the same colors and slanting for the rounded and rectangle view! I'll provide a color palette based on this approach. :)

**Comment by cstiens** [comment]
> Oh, I think we need this for Android to, yes?

Yes! I've added the ticket.

**Comment by cstiens** [comment]
@N-Pex I have an expanded color palette for the group chat avatars! Here it is—

F73D54 zom pink
FFF74F yellow
B2142F maroon
4FCAFF blue
86FF76 lime
CC4317 red-orange
8376FF purple

<img width="694" alt="screenshot 2017-09-15 10 58 02" src="https://user-images.githubusercontent.com/1434597/30492032-cb8a270a-9a04-11e7-8465-09196d988857.png">
