### ISSUE TITLE
enable media sharing for group chats

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#352]
even without encryption of messages, we should be able to do media upload/sharing via HTTP File Upload. Zom Android is currently doing it this way.

**Comment by chrisballinger** [comment]
It's possible with some refactoring. There are some hardcoded references to the message model used only for 1-1 chats. When in forced-plaintext mode 1:1 it will already upload unencrypted files via https. The bigger problem is that I'm not sure if the group chat view controller supports media because it was never tested.
