### ISSUE TITLE
UI to initiate group chat

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#360]

**Comment by cstiens** [comment]
@N-Pex Here's the flow for initiating a group chat from the '+' / new chat button on the convo screen. The second screen is the view you see when you select 'Create a group'.

After selecting the check in the second view, you are taken to the group chat. 

In regards to naming the group, I've removed this as a required step to start a group. I think auto generating a name that can be changed later will make for a better experience in starting a group. I'll make a separate ticket for the auto-generated name.

Also, this mockup shows Android standards for the header. Please disregard that. We should keep with the native iOS header we have.

<img width="942" alt="screenshot 2017-08-14 13 55 37" src="https://user-images.githubusercontent.com/1434597/29286542-05090bb6-80f8-11e7-8f83-793ab3e72d4f.png">

**Comment by N-Pex** [comment]
@cstiens Thanks, looks good! A few questions:

1. What happens in the case of multiple accounts? Should we only show contacts for the default account ("the me tab account") or should we show all the contacts, then when you select the first implicitly select that account and filter out all other contacts, or... ? Because I guess mixing contacts from your different accounts in the same group will lead to problems.

2. When you select a contact and it is added as a "pill view", will the contact disappear from the main list or do we still leave it there as well?

**Comment by cstiens** [comment]
> What happens in the case of multiple accounts? Should we only show contacts for the default account ("the me tab account") or should we show all the contacts, then when you select the first implicitly select that account and filter out all other contacts, or... ? Because I guess mixing contacts from your different accounts in the same group will lead to problems.

@N-Pex Yes. For now, I think we should only show contacts for the default account.

> When you select a contact and it is added as a "pill view", will the contact disappear from the main list or do we still leave it there as well?

When I contact is added as a 'pill', we would still leave them in the list, showing them as selected (the circle on the avatar with the check). Side note: If the circle on the avatar is complicated to implement for this view, we can entertain other visuals.

**Comment by cstiens** [comment]
I'm going to go ahead and close this. We'll make new tickets for enhancements. :)
