### ISSUE TITLE
Friend request in group chat: Buttons not working

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#376]
@N-Pex It's great to have this implemented! Currently the 'accept' and 'reject' buttons don't do anything. (build 89)

Also, as you can see in my screenshot, Rosa was sending a bunch of short messages before I approved her. So, I see the friend request a lot within 30 seconds. Is there a way we could limit how often we show it? That's a separate issue: #377

<img width="306" alt="screenshot 2017-09-01 09 51 14" src="https://user-images.githubusercontent.com/1434597/29975219-323264a0-8efb-11e7-8207-a66639b95669.png">

**Comment by N-Pex** [comment]
You are right, the buttons are not hooked up, they are just placeholders.

The reason for this is I was unsure what they actually do. The green one sends a friend request I guess, but the red one? Also, how do we show "Pending approval"?

I am not sure about the limit, need to do some digging. Currently it's comparatively easy to implement all this because of the 1:1 nature of "incoming message from unknown user" and "friend request view", i.e. we don't need to change anything in the db, just show our view instead of the message.
