### ISSUE TITLE
Easy message resend

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#43]
If a message did not go through, can there be an option to resend without having to retype?

**Comment by N-Pex** [comment]
Maybe add a custom action to outgoing messages, "resend"? Like this:

(BTW: @chrisballinger I get encryption errors in the feed here, although I think you implemented hiding of error messages, so that I would not have to use our branch for that(?) Any idea why?)

![simulator screen shot 6 dec 2016 15 52 11](https://cloud.githubusercontent.com/assets/5418622/20929937/08b7e58a-bbcc-11e6-9e14-ac4d6a01a642.png)

**Comment by davidchiles** [comment]
We put together something that looks like this. But is customizable to the contextual menu.
![screen shot 2016-12-09 at 3 27 03 pm](https://cloud.githubusercontent.com/assets/309772/21068123/b414b89a-be24-11e6-9d3e-df21100ebf77.png)
