### ISSUE TITLE
Disapproving Friend Request doesn't stop user

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#432]
Pressing [X] on an inbound request, turned the user to "pending request" mode. It didn't delete or block the contact, they could still send messages to me.

Also after pressing the [X] then I could open the contact, and it showed the "Waiting for your friend" and the refresh button.

EXPECTED BEHAVIOR: The inbound contact should be blocked from sending any more messages or friend requests.

**Comment by chrisballinger** [comment]
I don't know if permanently blocking users from friending you is desirable without additional user action. If you accidentally press the X, then there's no way to ever fix it. 

This is the proper way to implement blocking on the server: https://xmpp.org/extensions/xep-0191.html

**Comment by n8fr8** [comment]
Right, I don't mean blocking, but I mean that when you press "X" now it doesn't seem to work as expected. The user can still send you messages and harass you. 

@cstiens can we do more testing of this tomorrow? i might be related to the "waiting" refresh button but I am not sure.

We must also consider a more malicious threat model and adversaries than XMPP specs often consider. Just like with the design of Twitter or Facebook, these technical don't consider abuse of their system often in their implementation. So, not sure "proper way" is true... "The way the specification says to do it" perhaps.

**Comment by cstiens** [comment]
Yes. We can do more testing on this tomorrow.

**Comment by cstiens** [comment]
@n8fr8 Below are the results from our testing today. Next, we'll test Android to Android to see if the behavior differs in any way.

**CASE 1: iOS to iOS**
If the person in the pending approval state taps ‘refresh’ nothing happens if the friends hasn’t accepted or rejected the request. 
If the friend has rejected the friend request, the other iPhone still has a chat with that person that is pending approval. If they say ‘refresh’ the friend request is resent. But, they are unable to chat with that person until they are approved.

**CASE 2: Android to iOS—If iOS rejects friend request and Android taps refresh**
iPad and Samsung
Sam added iPad
iPad chose ‘x’ to friend request
The chat on Sam showed pending approval initially. Once the iPad selected ‘x’, the pending approval went away on the Sam. And they could send a chat. The chat, however, has a clock.

**CASE 2 (AGAIN) Android to iOS—If iOS rejects friend request and Android taps refresh**
iPhone to Droid
Droid added iPhone
iPhone chose ’x’ to friend request
On Droid, the pending approval did not go away when the iPhone tapped ‘x’, but the droid phone could still send messages. Messages show with the clock. When droid taps refresh, the pending approval goes away and all of her messages go through to the iPhone.

**CASE 3: Android to iOS—iOS does not accept or reject but Android taps refresh**
Droid and T’s iPhone
Droid added T
The droid showed pending approval when she opened the chat. T didn’t accept or reject the request.

Droid tapped refresh and can send messages to T, even though T hasn’t accepted or rejected the friend request. Pending approval UI still shows on the Droid. Message shows behind. (When Droid went to a different view in the app, the pending approval in the chat went away once opened again.)

When T opens the chat with Droid, it shows pending approval.

When Droid sends messages, she get double checks. T gets notifications with the new message. But when she opens the chat, it shows pending approval. 

T taps refresh on the pending approval view, the chats show up and she can write back to Droid. At this point, she HAS NOT accepted or rejected the friend request, and it is still shown in the convo view. The friend request does not go away when T sends messages.

If T taps ‘x’ on the friend request, it goes away and she’s still friends with Droid.

**Comment by tiffrobo** [comment]
**CASE 4: Android(Samsung) to Android(MotoX)—Sam does not accept or reject but MotoX taps refresh**
Carrie's Samsung and MotoX (2nd Generation)
MotoX added Samsung
The MotoX showed pending approval when she opened the chat. Sam didn’t accept or reject the request.

MotoX tapped refresh and Sam received a notification that they were friends with MotoX. Even though Sam had not yet accepted or rejected the friend request from MotoX, Sam's Friend request went away and MotoX was listed in their contacts. MotoX can send messages to Sam with double checks and still shows pending approval until Sam sends a message back. Sam can send and receive messages to MotoX. 
**Note: Keys are present in the profile view immediately**

**CASE 5: Android (MotoG Play) to Android (MotoX)—If MotoG Play rejects friend request** 
Moto G Play and MotoX (2nd Generation)
MotoX added Moto G Play
MotoG Play can tap on friend request and from profile view (no keys present) open a chat with MotoX. Where the text box usually is, instead shows 'add this friend?' Tap back arrow. 
Moto G Play chose ‘x’ to friend request

When Moto G Play taps 'X' friend request goes away and friend appears in their contacts. 
The chat on MotoX shows pending approval. Once the Moto G Play selected ‘x’, the pending approval still appears on the MotoX And they could send a chat. The chat, however, has one check. 
Moto G Play does not receive any message notification. After 2 minutes, MotoX types a new message. Pending approval goes away and they still receive one check. Moto G Play still receives no new message notification. 
**Note: No keys appear in either profile view.** 

**CASE 6: Android (MotoG Play) to Android (MotoX)—If MotoG Play rejects friend request and MotoX taps refresh****
Moto G Play and MotoX (2nd Generation)
MotoX added Moto G Play
MotoG Play can tap on friend request and from profile view (no keys present) open a chat with MotoX. Where the text box usually is, instead shows 'add this friend?' Tap back arrow. 
The chat on MotoX shows pending approval. MotoX And they could send a chat. The chat, however, has one check. 
Moto G Play chose ‘x’ to friend request
MotoX taps refresh

When Moto G Play taps 'X' friend request goes away and friend appears in their contacts. 
When MotoX taps refresh, pending approval goes away. Sends another message to Moto G Play, one check. 
**Note: No keys appear in either profile view**
If Moto G Play opens the chat with MotoX and sends a chat, 'Who is this?' They get a single check. Moto X never receives message or notification. Likewise, Moto G Play never receives messages or notifications.

**Comment by cstiens** [comment]
We need to test rejecting a friend request on iOS to make sure it's behaving properly. We didn't have any issues with the refresh button, but I want to make sure that if someone taps and 'x' on the friend request that it's doing the right thing.

**Comment by cstiens** [comment]
Closing this one. We're making a new ticket related to iOS friend blocking. #472
