### ISSUE TITLE
Better feedback when tapping 'refresh' from pending approval

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#436]

**Comment by cstiens** [comment]
<img width="770" alt="screenshot 2017-10-11 13 40 29" src="https://user-images.githubusercontent.com/1434597/31459859-14d955f4-ae8a-11e7-9c87-9500541cca4f.png">

If a user closes the chat and re-opens, hopefully they will be connected with their friend by then. If not, and they are still pending approval, this view should return to the initial state with the option to refresh.

**Comment by N-Pex** [comment]
Ok, added an animation that spins the label 5 times, then shows the check mark. The actual "sending" is pretty instantaneous (and has no callback) so the spinning time is pretty arbitrary here.

@chrisballinger Related stuff we need to look at: if your friend unfriends you, the you get a notification "you are now friends" (because we only have the "pendingApproval" flag to play with I guess). We need to implement a proper status flag for subscription status.
