### ISSUE TITLE
Missing messages in chat history

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#458]
@chrisballinger This is the issue we discussed today about T and Ro missing 8 messages about the Blade Runner soundtrack from the '103 Test' group.

**Comment by N-Pex** [comment]
@chrisballinger, @n8fr8  Hm, I think this is just a server config. The server has a default of returning 20 messages in history. We should probably bump that to way higher! Also, on Android I think we currently send "20" for history, we should implement that as on iOS and send the "since" header instead.

**Comment by cstiens** [comment]
I've also noticed, from using groups, that 20 messages is a pretty low number in a group chat when people are writing very short messages and sending multiple back to back.
