### ISSUE TITLE
Prompt to add a friend who is already your friend in group chat when photo is sent

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#521]
- T sent messages to group chat. R who is friends with T and has had previous conversations in single and group chat with contact T, sees the option to download the photo and a prompt asking "Is Tiff your friend?..."

- Any photo message sent from T to the group R saw this issue. We are only seeing this issue between T and R and only in one specific group. 

- It seems that the keys are updating pretty frequently. Though, neither side gets the option to verify. We're checking to see if R and T have the right keys for each other.

![img_9e5f4f930ac1-1](https://user-images.githubusercontent.com/30634981/35348512-e2d35f02-00fd-11e8-947c-dc4fc41d4522.jpeg)

Device: iPhone SE, iPhone 7
OS: 10.3.3, 11.2.2
App version: build 116

**Comment by tiffrobo** [comment]
An update to the ticket. 
When T sends an audio within the group, R sees the option to download. It is not auto-downloaded. 

![img_7a71458a4977-1](https://user-images.githubusercontent.com/30634981/35399667-680bf8d4-01ba-11e8-89e1-5bfd25cc6b52.jpeg)


Device: iPhone SE, iPhone 7
OS: 10.3.3, 11.2.2
App Version: 116

**Comment by N-Pex** [comment]
Related to room occupant changes, please retest in 118.

**Comment by cstiens** [comment]
Still happening in build 118.

**Comment by cstiens** [comment]
This is caused by a MAM refresh happening before the group can properly map to the correct JID for a room occupant. In build 121, we should only see this show up in 1 scenario. Though, in most cases, it will not happen. Here's the case:

If your friend goes to sleep (app is going to sleep in the background, log outs and logs back in, or goes into airplane mode) and you send messages. You send a photo to the group. When your friend logs in in the morning, he won’t be able to see you as a member in the group.

I'm going to test this now.

**Comment by cstiens** [comment]
@N-Pex I tested this case twice. The supplementary view saying you're not friends did not show up either time.
For a photo sent from a staging server account, 2 different things happened—
1) the link to the image showed up initially. Then I got the option to download the image. 
2) the link to the image showed up and I could open it with safari.

For a photo sent from a home.zom.im account, the image came through.

Either way, it seemed to map to the correct room occupant.
