### ISSUE TITLE
UI to pass admin status if the only admin leave a group

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#543]

**Comment by kckthx** [comment]
@cstiens I did this for iOS and Android
![group_choose-owner-android](https://user-images.githubusercontent.com/36669955/38270225-54b4d260-3748-11e8-88e3-b087c7486858.png)
![group_choose-owner-ios](https://user-images.githubusercontent.com/36669955/38270226-54ca991a-3748-11e8-860c-986f9cfedd90.png)

**Comment by N-Pex** [comment]
First version will be in build 127. We still have a few things to discuss here. Transfer is only done currently when hitting "leave" in the room occupants view, not when swiping and doing "delete" in the conversations list.

Also, it seems like the leaving person is not completely "cleaned up" and detached from the group. If the "new" owner re-adds the old owner, the old owner is still marked as an "owner".

**Comment by tiffrobo** [comment]
Yes, @N-Pex I'm seeing what you are seeing. 1) Transfer only done when user action is 'Leave' from the roster view. 2) Owner is still showing in group member's roster after leaving. 3) Can be re-added and with owner permissions.

How it is working:
- In a group chat with three 'admin' of group, only 1 'owner'
- Owner taps 'leave' and they get a prompt: 'Leave group?' 
------------ (@cstiens Should the word 'group' be capitalized?)
- Owner taps 'leave' and they get a second Prompt: 'Pick a New Owner Before You Leave' 
------------ (@cstiens should the 'a' be capitalized too?--purely because it will look better)
-Owner able to leave group. The group is no longer listed in their convo view. No longer recieve messages from group.

The new owner is given the 'owner permissions' (kick out, make admin, etc.)

---------(@cstiens @N-Pex Should the new 'owner' get a notification/indication they are the new owner?

Device: iPhone7, iPhone6, iPad 
OS: 11.2.2, 10.3.3, 10.3.2
App version: Build 127

**Comment by N-Pex** [comment]
Ok, fixed in 129.

**Comment by tiffrobo** [comment]
These are done and working:
- Prompt transfer message when group owner swipes to delete the group from Convo view
-  Capitalize group in 'Leave Group?'

Device: iPhone 6, iPhone 7,  iPad
OS: 10.3.3, 11.2.2, 10.3.2
App version: build 129
