### ISSUE TITLE
Share invite links through AirDrop

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#561]
We need to add "nearby" friend adding, and it seems like there is an easy API to do so, from iOS to iOS:
https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html

**Comment by tladesignz** [comment]
Example code from Apple:
https://developer.apple.com/library/content/samplecode/sc2273/Introduction/Intro.html

Doesn't look complicated. I expect 10 - 20 hours for this and #562.

**Comment by n8fr8** [comment]
Any thoughts about a custom URL Scheme? zomnb:// (Zom "nearby") or something like that?

**Comment by tladesignz** [comment]
Sounds just fine.

**Comment by tladesignz** [comment]
I suppose this should go here?
![simulator screen shot - iphone x - 2018-04-12 at 15 56 58](https://user-images.githubusercontent.com/117089/38681917-2b0e875c-3e6a-11e8-900c-25cd5921529a.png)

@N-Pex, could I have a short introduction, so I don't need to scratch my head about all of this works?

**Comment by N-Pex** [comment]
@tladesignz Correct, there's also a similar ZomNewBuddyViewController used in Onboarding.storyboard. The UI contains a toolbar where you can add a fourth button, "AirDrop" or similar (just copy one ot the others). THEN the icon needs to be set (it's a character from the material icons font, have a look at ZomNewButtonViewController:44). Yes, it's overly complicated, but it's implemented this way because 1. we wanted to use icons from the font and 2. The strings must not be "attributed strings" with the icon included in the storyboards, because then the translation scripts would be confused...

**Comment by tladesignz** [comment]
Ok. So there already *is* the "Share" button, which opens the system's "share" menu. (See screenshot above).
This can already be used to send the link via AirDrop. To add another button "AirDrop" would be quite strange, UI-wise.

What we should do instead is described here:
https://stackoverflow.com/questions/1108693/is-it-possible-to-register-a-httpdomain-based-url-scheme-for-iphone-apps-like

If we want to send a specific iOS-Zom URI with its own scheme, instead, that could get quite confusing.

**Comment by tladesignz** [comment]
Currently, the link to share is like this:
https://zom.im/i/#dGxhQGhvbWUuem9tLmltP290cj1kOWI3ZWE4MTdiZTk3YzNmNzE5YjRiMGE5Mjk5OGQ1ZGQzZThhMGYx

Which in turn links to this:
`xmpp:tla@home.zom.im?subscribe&otr-fingerprint=`

2 things here:

1. It seems, the fingerprint is missing. Any issues on the server?
1. Should Zom register for the `xmpp` scheme? Would that be a good idea?

Now, let's see how many spambots want to become my friend. :-)

**Comment by tladesignz** [comment]
Actually, we already support AirDrop.
Additionally, this is supersed by #590.
