### ISSUE TITLE
Non-friend profile from group

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#568]
If you're not friends with someone in a group, show a button in their profile to add them as a friend.
I'll get UI for this.

Android ticket: https://github.com/zom/Zom-Android/issues/450

**Comment by kckthx** [comment]
@cstiens @N-Pex 
![add-friend-ios](https://user-images.githubusercontent.com/36669955/38270159-358ba332-3748-11e8-86c1-f34ae39bf9d1.png)

**Comment by kckthx** [comment]
![add-friend-ios_0 0](https://user-images.githubusercontent.com/36669955/38327984-47c812a2-380f-11e8-9a48-a0cdc281bf66.png)
![add-friend-ios_0 1](https://user-images.githubusercontent.com/36669955/38327986-47dd19d6-380f-11e8-95d3-051f42d08b19.png)
![add-friend-ios_0 2](https://user-images.githubusercontent.com/36669955/38327987-47f1b44a-380f-11e8-938c-eb33f105e08b.png)
![add-friend-ios_0 3](https://user-images.githubusercontent.com/36669955/38327988-4806af62-380f-11e8-9dca-0880083c71dc.png)
@cstiens

**Comment by tiffrobo** [comment]
This is in! Looks and seems to function well. 
--One thing, the text says "requested" instead of 'added' which I think is better anyhow. 

The in-line text of the group chat even updated after I added an individual as a friend from their profile view.
I also see the 'new friends' as pending approval in my friends list. 

Device: iPhone7, iPhone6, iPad
OS: 11.2.2, 10.3.3, 10.3.2
App version: build 127

**Comment by tiffrobo** [comment]
This is in and now says "Added" instead of "Requested. See #584 Which is the desired word?

Device: iPhone 6, iPhone 7,  iPad
OS: 10.3.3, 11.2.2, 10.3.2
App version: build 129
