### ISSUE TITLE
Instructions are cut off after 2 lines

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#577]
![img_4756](https://user-images.githubusercontent.com/1434597/38583558-02c75a18-3cd9-11e8-9b26-84166b6f3ebc.PNG)

**Comment by tladesignz** [comment]
Ah, sorry, I shouldn't close it.

**Comment by tiffrobo** [comment]
This is fixed. 
Question: Should it read "Make sure the codes match your friend's latest Zom codes on **their device**." ?Instead of, "Make sure the codes match your friend's latest Zom codes on his or her phone." (This is how it reads now)

Device: iPhone 6, iPhone 7,  iPad
OS: 10.3.3, 11.2.2, 10.3.2
App version: build 129
