### ISSUE TITLE
List latest code first

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#578]
![img_4757](https://user-images.githubusercontent.com/1434597/38583626-39e166d8-3cd9-11e8-9158-0072c5beb430.PNG)

**Comment by tiffrobo** [comment]
These are a bit confusing. I am still seeing that some friends zom codes are in correct order. While others aren't. Some tell you when the code was updated and others don't. And some friends have no codes at all but have a green 'verified' check next to their name

![img_4823](https://user-images.githubusercontent.com/30634981/39057276-6b20886c-447e-11e8-84ae-833aa7c44440.PNG)
![img_4824](https://user-images.githubusercontent.com/30634981/39057277-6b378da0-447e-11e8-9a3e-704db0e900df.PNG)
![img_4822](https://user-images.githubusercontent.com/30634981/39057275-6b0b25f8-447e-11e8-929b-c966d077e423.PNG)


Device: iPhone 6, iPhone 7,  iPhone 6+
OS: 10.3.3, 11.2.2, 11.2.5
App version: build 129

**Comment by tladesignz** [comment]
Sorry for the confusion. I guess, we need to improve the design here.

1. First is a OMEMO code, second is OTR. OTR has no timestamp by which we could sort.

1. First is expired. That's untrusted, but not untrusted *new*, and it can't be reinstated by the user, therefore disabled toggle.

1. There are no *untrusted new* codes, therefore green. :-) Ok, this one should probably be red. But what about, if there are untruted codes, which are not new? Maybe we should rethink the phrasing here?

On the other hand: The codes seem to be cut off. That's definitely a bug.

**Comment by n8fr8** [comment]
Comments from the scrum:

- We should store when we receive OTR keys, so they have a timestamp just like OMEMO
- In some cases, older keys will not be expired, while newer keys will. This can be confusing, but it is just how it goes
- We also talked about labelling the keys OTR vs OMEMO with a small subtle label, so that users understand there is some key difference

**Comment by cstiens** [comment]
@tladesignz If there are no codes for a contact, we should show their avatar with no shield, and say 'No Zom codes for [name].' There's a bigger issue with the fact that you don't have codes for someone. We need to solve that separately. But, for the interim, to make this UI make sense, let's make this simple change. 

We still need a solution for handling if you only have 1 OMEMO key and its expired.

**Comment by tiffrobo** [comment]
Here's an updated UI mockup for displaying keys. 
Notable changes:
- Divider between OMEMO and OTR keys
- Badges for verification are different. Instead of the green check next to the trusted key, there is a green badge. 

![omemo_otr_01](https://user-images.githubusercontent.com/30634981/39545175-fe6ee230-4e15-11e8-904c-b2b37586c66f.jpg)
![badge-unverified](https://user-images.githubusercontent.com/30634981/39545274-491280e4-4e16-11e8-9c31-357c77c3dc47.png)
![badge-verified](https://user-images.githubusercontent.com/30634981/39545277-4926ec64-4e16-11e8-96ef-280723261671.png)

> @tladesignz If there are no codes for a contact, we should show their avatar with no shield, and say 'No Zom codes for [name].' There's a bigger issue with the fact that you don't have codes for someone. We need to solve that separately. See #594. But, for the interim, to make this UI make sense, let's make this simple change.

**Comment by cstiens** [comment]
I created a new ticket with a comprehensive list of the UI enhancements for this view: https://github.com/zom/Zom-iOS/issues/603
