### ISSUE TITLE
Only 1 OMEMO key for contact, but its expired

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#593]
When you send chats, you get errors. The error message says 'Unable to send message. We could not find any trusted devices.'

iOS build: 129
Device: iPhone7

![img_4842](https://user-images.githubusercontent.com/1434597/39269373-3fd8d556-4898-11e8-9ad7-c3abb950465c.PNG)

![img_4839](https://user-images.githubusercontent.com/1434597/39269330-205cc0ca-4898-11e8-8239-1b63ec949c48.PNG)

![img_4841](https://user-images.githubusercontent.com/1434597/39269331-206e5d1c-4898-11e8-99a7-ed325929c5ba.PNG)

**Comment by tiffrobo** [comment]
We've made progress on verification. I'm not seeing any expired keys for contacts anymore. I think because we now trust the latest key. 
We do still see the error appear for "can't find any trusted devices" which is related to having no keys for a contact. I will close this ticket for now. 

Device: iPhone 6, iPhone 7
OS: 10.3.3, 11.2.2
App version: build 133
