### ISSUE TITLE
Interim update to contact's profile view

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#597]
@N-Pex, @tiffrobo and I went over this last week. She can provide details. 👍 

- [ ] Remove 'Show More'
- [ ] Remove 'Verify'
- [ ] Remove 'Refresh session' if we aren't using OTR
- [ ] Add 'Start chat' to every profile view
- [ ] Add the number to zom codes (ex: View 2 Zom Codes or View 1 Zom Code)

**Comment by tiffrobo** [comment]
@N-Pex From the call today, we can make these changes to the profile view:

- [ ] Remove 'Show More' (Just show the last fetched key with QR code)
- [ ] Remove 'Verify Conact' 

- [ ]   Add 'Start chat' to every profile view
- [ ]   Add the number to zom codes (ex: View 2 Zom Codes or View 1 Zom Code)

I guess we will keep 'refresh session' since we are using OTR keys

![img_b31e94d78015-1](https://user-images.githubusercontent.com/30634981/39435494-2bb7a364-4c61-11e8-9f4d-8114ce03e83b.jpeg)

![img_4755](https://user-images.githubusercontent.com/30634981/39435576-6b5a8842-4c61-11e8-9d6e-dfa96cff2805.PNG)

**Comment by tiffrobo** [comment]
So I see either 'start chat' or 'refresh session'. Not both. 
I think 'start chat' is on all profiles unless you have no OMEMO key for the contact. 

Everything else in! 

Device: iPhone 7
OS:  11.2.2
Build: App version 130

**Comment by tiffrobo** [comment]
@N-Pex We want to show all three options on profile views, all the time. Thanks!

1. Start Chat
2. Refresh Session
3. View (number) Zom Code(s)

**Comment by tiffrobo** [comment]
@N-Pex I think this one slipped by. Per the last comment 20days ago. We wanted to show all three options on profile views, all the time. I'm not seeing 'Refresh Session' 
I do see the other two on all profile views though. 

1. Start Chat
2. Refresh Session
3. View (number) Zom Code(s)


Device: iPhone 7,  iPad
OS:  11.2.2, 10.3.2
App version: build 131

**Comment by tiffrobo** [comment]
@n8fr8 @chrisballinger We should have discussed this today, sorry. Can we remove 'Refresh Session' from the profile view? I know it only deals with OTR and currently only shows up sometimes. We are deciding to either add it to all profile views or remove it entirely.

**Comment by N-Pex** [comment]
@tiffrobo Unsure what the latest word on this is? Currently the logic seems to be:

* If we entered profile view via a group chat - show "Start chat"
* Else, if we entered via the chat view (message view controller) - show "Refresh"
* Else (if we entered via selecting a friend from the friends list) - show "Start chat"

**Comment by tiffrobo** [comment]
@N-Pex The final word is that we need to keep "refresh session" around. Originally we wanted "refresh session" to be added to every profile view. I think it makes more sense what you've listed above. Because the user sees a different action which only seems to be associated with the need to reconnect (refresh) with OTR. What do you think?

**Comment by tiffrobo** [comment]
@N-Pex We are getting rid of "refresh session".

**Comment by N-Pex** [comment]
Ok, fixed in 134.

**Comment by tiffrobo** [comment]
Not seeing "refresh session" in build 135. Everything else in the profile view is in. 

Device: iPhone 7, iPhone 6
OS:  11.2.2, 10.3.3
Build: 135
