### ISSUE TITLE
Verification UI Enhancements

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#603]
@tladesignz Here is a comprehensive list for the UI tuning for the verification view. I'm going to close the other ticket (#578) where we have feedback dispersed.

- [x] Text for 'Make sure the codes match...' cuts off on iPhone 6 still. It looks great on the iPad and iPhone 7 though.

- [x] For expired codes, since there is no action the user to take (for their friend's expired code), please remove the toggle if the code is expired. I think that it's disabled right now, but it looks like it's just off. So, let's remove it all together **_only if the code is expired_**.

- [x] Update icons -- 
for trusted, use green badge with the check (attached in @3x size and .pdf)
for untrusted, use red badge with exclamation point (attached in @3x size and .pdf)

[badges_v2.zip](https://github.com/zom/Zom-iOS/files/1996033/badges_v2.zip)

- [x] Divide OMEMO and OTR keys and add sub header (see mockup below)

- [x] If there are no trusted codes for a contact, change text to 'No Zom codes for [name].' 

<img width="392" alt="verification-enhance" src="https://user-images.githubusercontent.com/1434597/39934440-6dec2a2c-550b-11e8-9864-17235d15f253.png">

**Comment by tiffrobo** [comment]
Looking good here. 
@tladesignz Need to remove the toggle for untrusted codes.

- [ ] For expired codes, since there is no action the user to take (for their friend's expired code), please remove the toggle if the code is expired. I think that it's disabled right now, but it looks like it's just off. So, let's remove it all together only if the code is expired.

**Comment by tiffrobo** [comment]
Currently, want the toggles to be usable so I'll close this ticket!
