### ISSUE TITLE
Updates to Zom Code view

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#618]
@tladesignz We spoke about these updates on the call: 

- [x] Make OMEMO sub-header scroll with code
- [x] If there are No Zom codes for a user, update the badge by their avatar to the red with the exclamation point. 

![img_5040 2](https://user-images.githubusercontent.com/30634981/40943841-319276a6-6818-11e8-85e7-dff1bbb46ff6.PNG)
![img_5041](https://user-images.githubusercontent.com/30634981/40943842-31a68b5a-6818-11e8-84fd-dd8641fd8740.PNG)

Device: iPhone 7
OS:  11.2.2
App version: build 131

**Comment by tladesignz** [comment]
Sorry, I don't want to make it non-fixed. Apple has put a lot of thought and a lot of work into the section headers, so they stay on top as long as the section isn't gone completely.
I don't want to be complicit in destroying this, just because we didn't think our design through, completely. Instead, I gave the headers an explicit white background, so the section rows don't shine through, anymore. Together with the plentiful padding, this looks quite ok to me. Please test yourself, if you can life with that! :-)

**Comment by tiffrobo** [comment]
Okay. I'll test the headers when we get a new build. I have one more update.

- [ ] If there are No Zom Codes for a contact, please remove this copy: "Make sure the zom codes match your friend's latest Zom codes on his or her device."
