### ISSUE TITLE
User names / account creations needs to be consistent btw iOS & Android

### ISSUE THREAD

**Issue by jodiejones** [zom/Zom-iOS#89]
When Tenzin Lobsang tried to create a new account in iOS with tenzinelle she received a notification saying account creation had failed. This is b/c she has previously created an account with this user name but in android an account will still be created for her. There needs to be consistency across platforms on this issue.

Also, right now I show up as my username _kateiszoming_ in iOS but in Android I appear with my full account name_ kateiszoming.a5abfd20_. There should be consistency across platforms and ideally I'd be able to use _kateiszoming_ as my Zom screen name even though my full account is _kateiszoming.a5abfd20@dukgo.com _

**Comment by n8fr8** [comment]
@davidchiles we really need this support on iOS.... even if we don't use the last part of the key fingerprint, we at least need to randomly generate a tag to the username to guarantee a new unique account. 

This is a big issue since many Tibetans will enter "tenzin" or "pema" (as examples of very common names) so we should handle this kind of situation by default.

**Comment by davidchiles** [comment]
Progress here https://github.com/ChatSecure/ChatSecure-iOS/pull/498

**Comment by n8fr8** [comment]
Did this make it into the last testflight build @N-Pex  ?
