### ISSUE TITLE
Push Message Retention

### ISSUE THREAD

**Issue by dhongmar** [zom/Zom-iOS#95]
On the IOS front, when I send a message using Push, I get a message on the IOS saying that someone one wants to chat with me but not the message itself. Would it be possible to resend the same message when the chat is connected so as not to loose that message.

**Comment by n8fr8** [comment]
In theory, it does connect in the background, login, establish an OTR session and get any messages that are there. We are working on smoothing out the process, so that the message is queued, and sent when the OTR session is refreshed. So, in short, yes, that is the goal, and we should get it to work in the very near term.

For now, the push support should be seen more like a "knock" or a "ring" to request a secure chat, and not a background message.

**Comment by n8fr8** [comment]
This is now working, at least between Android and iOS. We queue messages on Android until we see the iOS contact come online and establish an encrypted session.
