### ISSUE TITLE
Cannot use latest version of Zom on iPhone 4S iOS 8.4

### ISSUE THREAD

**Issue by rosagp** [zom/Zom-iOS#97]
I downloaded the latest version of Zom for iPhone 4S with iOS 8.4 and after I open the app I get this screen:

![img_7969](https://cloud.githubusercontent.com/assets/4604279/14479923/d11c815c-00f1-11e6-9970-9cf125b8b3d3.PNG)

After I tap Skip, the next screen I get is this:

![img_7970](https://cloud.githubusercontent.com/assets/4604279/14479958/fdcc02ae-00f1-11e6-8ee8-80d274664347.PNG)

**Comment by chrisballinger** [comment]
This may have been fixed upstream in ChatSecure

**Comment by rosagp** [comment]
Does that mean it is fixed for Zom and can be resolved in the next build?

**Comment by chrisballinger** [comment]
Most likely

**Comment by n8fr8** [comment]
@chrisballinger N-Pex is having challenges building form upstream. We need to get a new build today.

**Comment by N-Pex** [comment]
I think I got it building now. After trying a lot of different things, I think the problem was the project referencing Pods_ChatSecureCore.framework, whereas I have Pods.framework. Are you guys using the 1.0.0.beta.7 version of CocoaPods or what might be the difference?

Anyway, trying to get a build out, but will mostly be upstream changes at the moment.

**Comment by n8fr8** [comment]
That's fine since there seem to be a lot of good upstream changes! Thanks for the update.

**Comment by N-Pex** [comment]
Ok, good. Uploaded now. Note that 1) I was kind of in the middle of changing "lock" to the "shield", so the code I built from is not checked in at the moment (Monday), and 2) because of 1) the icons are now just old icons for "lock" and "unlock" that happened to be included as resources already... =)

**Comment by n8fr8** [comment]
@rosagp can you try the latest testflight and see if it is better? I think you are getting stuck on the push notification screen due to a missing button!

**Comment by n8fr8** [comment]
Working well now!
