### ISSUE TITLE
Sending invite link from iOS to Android through email

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#98]
Tried between iOS and Android.
User 1: 1Plus OS version 5.1.1
User 2: iTouch OS 9.3.1

User 2 (iOS) shared link through gmail with User 1 (Android).
When User 1 (Android) clicked on the link, User 2 (iOS) appeared in the friend list but User 1 (Android) didn't appear in User 2's (iOS) friend list and didn't get approval notification.

Couldn't establish chat.

**Comment by gekhung** [comment]
User 1: iPhone 6 version 8.3
User 2: Zenfone 5.0

User 1 (iOS) sent invite link to User 2's (Android) gmail. User 1 (iOS) appeared in User 2's (Android) friend list but User 1 didn't get any approval notification.

Couldn't establish chat.

**Comment by chrisballinger** [comment]
@gekhung On the main screen of the app do you see an inbox icon next to the compose button?

**Comment by gekhung** [comment]
Nope, it didn't appear both on iTouch and the iPhone.

**Comment by n8fr8** [comment]
Are you sure the iPhone 6 users was logged in? Wasn't there an issue with logging in on 8.3?

**Comment by n8fr8** [comment]
also @chrisballinger do you still have an 8.x device?

**Comment by chrisballinger** [comment]
The iPhone 4S that was sent out to me had iOS 7.x, but since Apple had stopped signing 8.x by that point I had to install 9.x in order to run Zom, since it has a minimum version of 8.0.

When I'm trying to understand this flow:

> User 1 (iOS) sent invite link to User 2's (Android) gmail. User 1 (iOS) appeared in User 2's (Android) friend list but User 1 didn't get any approval notification.

When you send an invite link over Gmail, it doesn't automatically approve any JID because it can't know the JID of the person receiving the invite in advance. When Android adds the iOS user, it should send a subscription request over XMPP to the corresponding iOS account contained in the invite. Then the iOS client will see an inbox icon on the top left of the home screen, where you then need to approve the request before you can chat.

Possible issues there are:

1. The iOS client is offline and cannot receive the subscription request. It should receive the request as soon as the app goes online again.
2. The Android client isn't sending the subscription request, or it isn't received or processed by the server correctly.
3. The inbox icon is not visible for whatever reason.

Slightly related to this, but in the other direction, the invite URLs cannot launch the app prior to iOS 9. All http links are handled by Safari. We could add a xmpp: URI to the /i/ destination page to resolve this but, of course, it would only work after the app is installed.

**Comment by n8fr8** [comment]
Thanks for the clear breakdown of this issue, Chris! At the very least, we should start with making sure there is no UI issues with the smaller iPhone screens.

Otherwise, one thing we had talked about was to auto accept subscriptions, or at least support receiving messages from people you are not subscribed/subscribing to, and then focus on making blocking/deleting users easy and simple. Opt-out vs opt-in. On Android this has proven much easier from a usability perspective, and since XMPP jid's aren't generally known or searchable easily, it makes more sense. Most of the sharing of identity is with trusted sources.

**Comment by chrisballinger** [comment]
I think there are potentially serious security implications related to automatic acceptance of subscription requests.

We will be developing an improved UI for approving requests where they appear in your conversation list with a clear ✅ or 🚫, to remove the need for the inbox icon. For Zom we would be open to exposing an option that allows automatic accept, but it's not on our immediate development timeline.

**Comment by n8fr8** [comment]
Either way the current user experience is a real hangup for new users.
We need to keep the focus there, and not on people with preexisting
rosters like from Gmail or Facebook as we historically have done. To
start a secure conversation with a new contact is still too many taps.

If you can add some preference defaults that can be easily overridden by
Zom that would be great.
